### PR TITLE
K3d local registry pod spec updated

### PR DESCRIPTION
**Pull request by wjayesh**
## Describe changes
I fixed a problem with the k3d cluster when a default container registry is used. 
The pod spec should have the `k3d-zenml...` prefix on the image name for it to be pulled successfully inside the pod. This PR adds that.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by schustmi** [comment]
Can you explain in a little more detail what the issue was here? From what I know this worked fine with the existing code, what lead to the failure and why does this prefix solve it?

The final image name would be something like `k3d-zenml-kubeflow-registry.localhost:5000/zenml:some_pipeline`, which seems very strange to me

**Comment by wjayesh** [comment]
@schustmi 
In the k3d [docs](https://k3d.io/v5.4.4/usage/registries/#testing-your-registry), it says:
> Note: as per the explanation in the [preface](https://k3d.io/v5.4.4/usage/registries/#preface-referencing-local-registries), you could replace k3d-registry.localhost:12345 with localhost:12345 in the docker tag and docker push commands below (but not in the kubectl part!)

It means that the image name should indeed be: `k3d-zenml-kubeflow-registry.localhost:5000/zenml:some_pipeline` and not just `localhost:..`. I also verified that it didn't work for me earlier (after a user raised this as a problem on Slack).

**Comment by schustmi** [comment]
@wjayesh You're right, I just ran some additional tests:
- When using a local container registry with port 5000 (`container_registry.uri="localhost:5000"`), the pods can pull images both using `localhost:5000/image-name:tag` as well as `k3d-zenml-kubeflow-registry.localhost:5000/image-name:tag`
- When using a different port, only the latter works. Not sure why that is, but your fix makes it work with all additional ports. Great job!

I have one additional suggestion to make this even cleaner: Instead of checking `stack.container_registry.flavor== ContainerRegistryFlavor.DEFAULT.value`, we can use the property that checks if a container registry is local: `stack.container_registry.config.is_local`

**Comment by wjayesh** [comment]
Thanks for testing the fix, Michael! I have added your suggestion.

**Review by schustmi — APPROVED** [review]
LGTM!

**Pull request merged**
