### PR TITLE
Remove Python 3.7 Support

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
Python 3.7 reached its end of life on June 27th, 2023.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

### CODE REVIEW

**Comment by fa9r** [comment]
Frozen for now in favor of #1650

**Comment by fa9r** [comment]
Reopening since #1695 upgraded `kfp-tekton` to a newer version that is no longer Python 3.7 compatible

**Review by strickvl — APPROVED** [review]
❤️🗑️

**Review by stefannica — APPROVED** [review]

**Review by AlexejPenner — APPROVED** [review]
What I could see looks good to me!

**Pull request merged**
