### PR TITLE
Fix class resolving in Colab.

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
Class resolving previously failed on Colab when importing steps from other files.

E.g. in ZenBytes we do:
```
!git clone https://github.com/zenml-io/zenbytes.git  # noqa
!mv zenbytes/steps .
!mv zenbytes/pipelines .

from steps.evaluator import evaluator
from steps.importer import importer
from steps.sklearn_trainer import svc_trainer

digits_svc_pipeline = digits_pipeline(
    importer=importer(), trainer=svc_trainer(), evaluator=evaluator()
)
```

which failed with `RuntimeError: Main module was not started from a file. Cannot determine the module root path.`
raised in `get_source_root_path` in `is_third_party_module` in `resolve_class`.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by schustmi** [comment]
@htahir1 ran into this exact issue yesterday, and it is fixed by doing a `zenml init`. What do the colab files in your case get resolved to after this change?

Overall the logic here seems a little flawed to me: This change essentially says that when running in colab, nothing can be a third party module?

**Comment by fa9r** [comment]
@schustmi thanks for the hint, `zenml init` fixes this indeed.

**Comment by fa9r** [comment]
@schustmi something about `is_third_party_module` raising an error still seems odd to me though.

**Comment by schustmi** [comment]
Yes I agree. Maybe we need a special case here that detects that we're running in a notebook environment and maybe uses the notebook path as the "source root"?

**Pull request closed without merging**
