### PR TITLE
Validate Stack Before Provision

### PR DESCRIPTION
**Pull request by safoinme**
## Describe changes
This call the `validate function`  when the stack is provisioned which will validate if the stack configuration is correct! 

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by schustmi — APPROVED** [review]
LGTM. Maybe something we can add a test for?

**Comment by safoinme** [comment]
@stefannica Before 0.20 the validation was done at the stack register level. the validate function was being called pre-register stack. while now that isn't called anymore. Do you think we should be back to the register function or provision?

**Comment by safoinme** [comment]
@schustmi a test for this would be creating a stack with a remote orchestrator and no remote registry or do you think there is a better way to test it?

**Comment by schustmi** [comment]
@safoinme The easiest test to me would be to create a stack object with a mock `validate` method and make sure that it gets called when calling `stack.provision()`

**Pull request merged**
