### PR TITLE
Fixed broken link returned form pipeline runs

### PR DESCRIPTION
**Pull request by AlexejPenner**
## Describe changes
At the end of every pipeline run, the URL in the UI is printed. This link broke in our latest release, as part of the route has changed in the dashboard. This has been fixed within this PR.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by fa9r — CHANGES_REQUESTED** [review]
I don't think this change will work, which endpoint is this supposed to hit?

I found the following endpoints in the routers:
- `f"/projects/{client.active_project.name}/pipelines` -> `list_project_pipelines`
- `f"/projects/{client.active_project.name}/runs` -> `list_runs`
- `f"/pipelines/{str(pipeline_id)}/runs"` -> `list_pipeline_runs`

In particular, the old URL should have hit the last endpoint so not sure why this would be broken in the first place.

**Comment by AlexejPenner** [comment]
> I don't think this change will work, which endpoint is this supposed to hit?
> 
> I found the following endpoints in the routers:
> 
> * `f"/projects/{client.active_project.name}/pipelines` -> `list_project_pipelines`
> * `f"/projects/{client.active_project.name}/runs` -> `list_runs`
> * `f"/pipelines/{str(pipeline_id)}/runs"` -> `list_pipeline_runs`
> 
> In particular, the old URL should have hit the last endpoint so not sure why this would be broken in the first place.

Worked for me, keep in mind the frontend build routes differently. 

`http://127.0.0.1:8237/projects/default/pipelines/71b95127-39e0-4295-8020-fafb5316b659/runs`

This is where it would point on my local deployment. 

Check it out here as well:

`https://demo.zenml.io/projects/default/pipelines/7e99264b-c969-4e74-b261-af83143e79c7/runs`

**Comment by fa9r** [comment]
Ah yeah you are right, this is not hitting the API directly, I see. Looks good then.

**Review by fa9r — APPROVED** [review]

**Review by safoinme — APPROVED** [review]
LGTM!

**Pull request merged**
