### PR TITLE
Fix `alembic_start` migration if tables exist

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
Users migrating from ZenML versions 0.20.0-0.20.5 might already have the new ZenML tables in which case the `alembic_start` migration will fail with error `(pymysql.err.OperationalError) (1050, "Table 'projectschema' already exists")
`. 

To prevent this, I added a simple check that skips the `alembic_start` table creation statement if the `projectschema` table already exists.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by AlexejPenner** [comment]
It may be the vacation fog, but I don't fully understand why the projectschema would raise this error but none of the other tables raise this. Is this related to our renaming of the project table to workspaces somewhere down the line?

**Comment by fa9r** [comment]
@AlexejPenner any of the tables would raise this, `projectschema` is just the first one we create

**Comment by fa9r** [comment]
Implementation-wise I just did it lazily in that we simply finish the migration if any of the tables already exist (which I check using `projectschema`). I guess we could have `if X in tables: op.create_table(X)` instead but it shouldn't make a difference IMO.

**Review by AlexejPenner — APPROVED** [review]
:seal:

**Review by stefannica — APPROVED** [review]

**Pull request merged**
