### PR TITLE
Unpin `requests` dependency

### PR DESCRIPTION
**Pull request by strickvl**
We pinned requests on account of this: https://github.com/docker/docker-py/issues/3256

New versions have been released which fix this, so I just remove the restriction on requests since it's such a fundamental library and it was blocking other dependency upgrades / usage.

### CODE REVIEW

**Review by avishniakov — APPROVED** [review]

**Comment by stefannica** [comment]
@strickvl I think you can close it in favor of this PR I already had open: https://github.com/zenml-io/zenml/pull/2843

**Review by stefannica — APPROVED** [review]

**Comment by stefannica** [comment]
I don't think removing the requests pin is enough to address the reason it was added there in the first place (https://github.com/docker/docker-py/issues/3256). Namely, this still fails for me:

```
pip install  "docker==6.1.3"
python -c "from docker.client import DockerClient; DockerClient.from_env()"
```

but this works:

```
pip install  "docker==6.1.3" "requests<2.32.0"
python -c "from docker.client import DockerClient; DockerClient.from_env()"
```

**Comment by stefannica** [comment]
The only `docker` version that works with `requests` higher than 2.32.0 is `docker==7.1.0`, but that has the unfortunate side-effect that it's no longer compatible with docker-compose, which we rely on to run our CI.

**Comment by strickvl** [comment]
No longer needed since we have #2843

**Pull request closed without merging**
