### PR TITLE
Fix Azure Integration Imports and Improve Flavor Registration Error Handling

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
The Azure artifact store flavor imported the service connector which required. the Azure library.

This is very problematic since it would lead to an error during flavor registration, which would mean that subsequent integrations would be missing, e.g., `zenml model-deployer flavor list` would return an empty list even if all deployer integration requirements were installed.

To prevent integration issues like this to affect other integrations in the future, I also wrapped the flavor registration logic in our flavor registry in a try-catch block.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by fa9r** [comment]
[fa9r](https://github.com/fa9r) prevented a review from [schustmi](https://github.com/schustmi) now

**Review by strickvl — APPROVED** [review]
Looks good to me, and I'd hit this exact issue earlier in the week in a fresh environment.

**Comment by bcdurak** [comment]
I guess, I was a bit too late to press the comment button 😄 In any case, some thoughts that I wanted to share anyhow:

The changes look good to me as well. However, I am confused about the implications of this issue and am unsure if this is the ultimate solution.

When we initialize the store, we always try to register all the integration flavors. From what I understood, the Azure artifact store flavor itself imported constants from the connectors module which required the Azure library to be installed, thus it failed. However, this should not only just make the flavor registration fail but cause a store initialization error as well, meaning the first time you initialize the SQLZenStore [_it is gonna fail_](https://github.com/zenml-io/zenml/blob/cdde7ea2a2af7d1406cae178ad1a2f4d8a77fb06/src/zenml/zen_stores/base_zen_store.py#L145). The confusing part is: since this is the last step of the initialization process, you were able to keep using ZenML even though the main ZenStore has failed to migrate the flavors with an error during the initialization process. 

It means, this was a relatively silent failure and these changes save other integrations but make the failing integration fail even more silently now. I think, we really need to implement some sort of testing mechanism to make sure this does not happen to our integrated flavors now.

**Comment by bcdurak** [comment]
also, #unblock-@schustmi 😄

**Pull request merged**
