### PR TITLE
Feature/new compute gif

### PR DESCRIPTION
**Pull request by AlexejPenner**
## Describe changes
I created a new gif to show resource settings.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — APPROVED** [review]

**Comment by strickvl** [comment]
@AlexejPenner btw have we calculated just how many GB someone will / would have to download just to view our README? this one's 13MB, so would it be in the order of ~80 MB someone needs just to load our README? That feels like a lot...

**Review by htahir1 — CHANGES_REQUESTED** [review]
@strickvl also makes a good point. Maybe we need to compress the GIF's and not make them so big. it would help a lot. content is good!

**Comment by AlexejPenner** [comment]
@htahir1 @strickvl I compressed them now, I am not too impressed by their quality though :disappointed:

**Comment by strickvl** [comment]
yeah the quality isn't really particularly good any more

**Review by htahir1 — APPROVED** [review]
I am going to merge this until we take more action as i think its good enough and we get the new GIF and slightly reduced sizes

**Comment by htahir1** [comment]
Actually nevermind the new GIF is already there for some reason

**Pull request closed without merging**
