### PR TITLE
Use docker credentials in the skypilot orchestrator

### PR DESCRIPTION
**Pull request by stefannica**
## Describe changes
When the container registry is linked to a service connector or configured with docker credentials, these should be used to configure the SkyPilot task to fetch the image inside the VM.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — APPROVED** [review]
it looks good ! but i haven't tested it either, thanks for getting rid of my gnarly code

**Review by safoinme — APPROVED** [review]
Looks good

**Comment by stefannica** [comment]
Successfully tested using two different stacks:

* AWS skypilot + AWS ECR container registry + S3 artifact store (all linked to the same AWS connector)
* AWS skypilot + S3 artifact store (all linked to the same AWS connector) + Google GCR container registry (linked to a GCP connector)

This shows that the Docker credentials are successfully pulled from the service connector and configured inside the SkyPilot node regardless of the credentials origin.

**Comment by stefannica** [comment]
Using the Skypilot orchestrator with AWS credentials coming Service Connectors still has some problems due to how AWS credentials are transferred by SkyPilot inside the AWS EC2 VM. Details here: https://github.com/skypilot-org/skypilot/issues/2737

**Pull request merged**
