### PR TITLE
Examples are automatically pulled if not present before any example command is run

### PR DESCRIPTION
**Pull request by AlexejPenner**
…li command is run

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Examples are automatically pulled if not present before any example command is run

### CODE REVIEW

**Review by htahir1 — APPROVED** [review]
Yup that works!

**Review by htahir1 — COMMENTED** [review]
Ah actually it does not work for me.

From a fresh install I do:

```
zenml example run quickstart
```

It says:

```
➜ zenml example run quickstart
Error: Example quickstart is not installed at /home/hamza/workspace/zenml/zenml/zenml_examples)
```

The leading `)` is weird.

Also doing `zenml example run quickstart` subsequently causes the same problem

**Comment by AlexejPenner** [comment]
In this context pulled means that the examples are present in the global zenml folder. As we are not sure from where the user is running zenml example * we don't know if he actually wants it copied to his current working directory. In this case I will add a better lof message telling the user to run zenml example pull with the desired destination folder (zenml_examples being the default)

**Comment by htahir1** [comment]
From the users perspective, doesnt it make sense to `just work`? Like just let it run and pull to the default?

**Comment by AlexejPenner** [comment]
You're right. 
How about if without -f, the user needs to confirm that it will be copied into his cwd.
With -f, its pulled, copied into cwd and then run.

**Comment by htahir1** [comment]
that also works. We should reflect the example readme and all the individual examples readmes to reflect this if we take that route though :-)

**Comment by AlexejPenner** [comment]
Implemented the functionality of pulling if not present. Now if you do `zenml example run quickstart` it will use the cli context to forward to `zenml example pull quickstart` with the same parameters if there is no example present locally. 

Do you think its alright to use cli context for this, or should I go back and put the functionality of the pull command into a separate callable function?

**Pull request merged**
