### PR TITLE
Fix the mismatch KFP version between Kubeflow and GCP integration

### PR DESCRIPTION
**Pull request by safoinme**
## Describe changes
Use the same KFP version between GCP and Kubeflow Integration. Now creating a docker image with both integrations fails.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by schustmi — APPROVED** [review]

**Review by fa9r — CHANGES_REQUESTED** [review]
I think this will create a new dependency conflict between Kubeflow and (Seldon, Kubernetes) since all of them use `kubernetes` package under the hood. Maybe @stefannica knows more about this?

**Comment by schustmi** [comment]
> 

Isn't seldon etc all mostly tested with the KubeflowOrchestrator (which isn't changed in this PR) and not at all with Vertex (which now should use the same, tested version of KFP)?

**Review by fa9r — APPROVED** [review]

**Comment by fa9r** [comment]
You're absolutely right, for some reason I thought the KFP version changed, nevermind 🤪

**Review by AlexejPenner — APPROVED** [review]
Tested on vertex and works for me - LGTM

**Pull request merged**
