### PR TITLE
add alpha as server deployment type

### PR DESCRIPTION
**Pull request by wjayesh**
## Describe changes
I created an alpha server deployment type to help track our cloud alpha usage.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
Ok you put it in the Enum but when is it used?

**Comment by wjayesh** [comment]
@htahir1 It will be used as the server deployment type in the managed-servers repo. Passed as a value to the helm chart here: https://github.com/zenml-io/managed-servers/blob/d65012baaf3204abd57dbac8b27ec6903d736fc9/zenserver/zen_server.tf#L50

**Comment by htahir1** [comment]
hmm ok i dont see it used anywhere :-D but i think if you know where it is its fine

**Comment by wjayesh** [comment]
@htahir1 yes, it isn't used as of now. The server deployment type for all our alpha deployments is "gcp" currently but once this change is merged I can change it to "alpha".

**Review by htahir1 — APPROVED** [review]

**Pull request merged**
