### PR TITLE
Add support for Label Studio OCR config generation

### PR DESCRIPTION
**Pull request by shivalikasingh95**
## Describe changes
Hi, as part of the MLOps competition, I wanted to use Label Studio for OCR labelling task. Since ZenML currently supports only generation of template for image classification and object detection labelling tasks, I implemented support for OCR to support my use case. I thought of contributing this back since it might be useful for others too.  
As a user of zenml, I felt that all the features supported by label studio should be accessible via the zenml integration as well. So I'd be happy to submit a similar PR to support other kinds of labelling tasks supported by label studio if you guys would be interested in it.

Do let me know if the current PR requires any changes.

However, in case, this PR is not something you guys are looking to add at the moment then do let me know. I will revoke it. 

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by htahir1** [comment]
@shivalikasingh95 This is a great contribution and im sure @strickvl will have some thoughts when he seens it. For now, what I can say is that we have one minor docstring quality check that failed

`src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py:generate_basic_ocr_label_config:114: DAR101: Missing parameter(s) in Docstring: - labels`

Could you add labels to that docstring?

**Comment by strickvl** [comment]
If it's not too much of a pain, could you also write a unit test validating the output of the label config utility function you've added? You'll see a template for how to do that exists already in our `tests` folder, so it shouldn't be too much hassle I hope!

As for the rest, I'll check it properly in the morning, but it looks great at first glance!

**Comment by shivalikasingh95** [comment]
> @shivalikasingh95 This is a great contribution and im sure @strickvl will have some thoughts when he seens it. For now, what I can say is that we have one minor docstring quality check that failed
> 
> `src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py:generate_basic_ocr_label_config:114: DAR101: Missing parameter(s) in Docstring: - labels`
> 
> Could you add labels to that docstring?

Sure @htahir1 I'll fix this!

**Comment by shivalikasingh95** [comment]
> If it's not too much of a pain, could you also write a unit test validating the output of the label config utility function you've added? You'll see a template for how to do that exists already in our `tests` folder, so it shouldn't be too much hassle I hope!
> 
> As for the rest, I'll check it properly in the morning, but it looks great at first glance!

Sure thing @strickvl! I'd be happy to write the unit test :) Will update the PR shortly!

**Comment by htahir1** [comment]
@shivalikasingh95 Thank you! When u hav written the test just ping me and ill merge this!

**Comment by shivalikasingh95** [comment]
> @shivalikasingh95 Thank you! When u hav written the test just ping me and ill merge this!

Hi @htahir1 and @strickvl apologies for the delay at my end. Had to take last week off due to some reasons. I have updated the PR with the required changes. Let me know if anything else needs to be updated.

There are couple of other PRs that I'm interested in submitting for Label studio integration:
1. Similar to current PR, add label config support for common NLP tasks supported by label studio
2. Fixing sync storage issue --> at the moment, using zenml integration, it's not checking if a storage with that name already exists and just syncing that. It always ends up creating a new storage & then running sync which leads to duplication of labelling tasks in label studio
3. Adding support for local storage - at the moment, only cloud storage is supported via zenml for label studio. I'd like to add support for importing data for labelling via local storage as well since label studio already supports this.

Let me know, if you guys would be okay with this then I can take these up one by one in the coming days.

**Comment by shivalikasingh95** [comment]
> Hi @htahir1 and @strickvl apologies for the delay at my end. Had to take last week off due to some reasons. I have updated the PR with the required changes. Let me know if anything else needs to be updated.

Hi @htahir1 and @strickvl just a gentle reminder to do a quick review of the PR whenever you guys find the time -- in case my previous message got missed earlier in the middle of the bot notifications :)

**Comment by htahir1** [comment]
@shivalikasingh95 Sorry for the delay here. @strickvl is the only one who can validate the test and hes on vacation and only back in a few days. We will take a look and merge this week!

**Comment by shivalikasingh95** [comment]
> @shivalikasingh95 Sorry for the delay here. @strickvl is the only one who can validate the test and hes on vacation and only back in a few days. We will take a look and merge this week!

@htahir1 No problem, thanks for the update! I just thought of checking once from my end. Will wait for @strickvl to get back :) No worries!

**Review by strickvl — APPROVED** [review]
Thank you for this contribution, and for adding in the tests. This looks good to me and I'll get it merged in now.

**Comment by strickvl** [comment]
@shivalikasingh95 for the other suggested contributions, points 1 and 2 would probably be best to start with right now. The third one will also be welcomed, but it might interact or be improved by something else that's changing in the codebase right now so maybe give it a couple of weeks before you take a look at that.

Some of the Label Studio config auto-generation might be a bit more tricky, however, so feel free to check in with us if you have any questions. Just try to be as generic as possible and you should be fine.

**Comment by htahir1** [comment]
@shivalikasingh95 Thank you for your contribution! I have posted about it here: https://www.linkedin.com/posts/hamzatahirofficial_mlops-activity-7010547706611834881-2_37?utm_source=share&utm_medium=member_desktop :-) 

Again congrats on your awesome submission!

**Pull request merged**
