### PR TITLE
Remove `force` flag from secrets managers' implementation

### PR DESCRIPTION
**Pull request by strickvl**
We had an inconsistently used `force` flag which was defined in the base secrets manager. I removed this, since we already have checks at the CLI level to confirm that people really want to delete all secrets.

I added some missing license statements where I found them.

I also looked to see if there were any tests that were going to break as a result of these changes, but I see that we currently have no tests covering these changes (or really *any* effective testing of our cloud secrets managers).

### CODE REVIEW

**Review by schustmi — CHANGES_REQUESTED** [review]
I think the GitHubSecretsManager might still need an update, otherwise looks good

**Comment by strickvl** [comment]
Ah yes, I forgot that that was even a thing!

**Review by schustmi — APPROVED** [review]

**Review by AlexejPenner — APPROVED** [review]
Good Catch :)

**Comment by strickvl** [comment]
I don't think this PR will include any more tests, @AlexejPenner. I think that'll come either with #ENG-934 or some more extended integration tests.

**Comment by AlexejPenner** [comment]
> I don't think this PR will include any more tests, @AlexejPenner. I think that'll come either with #ENG-934 or some more extended integration tests.

Oh wasn't talking about new tests, its just that it was failing unit tests because there is a force flag being passed in the tests: https://github.com/zenml-io/zenml/runs/6914867938?check_suite_focus=true

**Pull request merged**
