### PR TITLE
Track System Info and Python Version of Pipeline Runs

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
I added two dicts `client_environment` and `orchestrator_environment` as attributes into pipeline run models and schemas to track system info and python versions of runs.

E.g., runs on my local machine now have the following environment data associated with it (similar for both client and orchestrator since I'm running locally):

```
{
    "environment": "native",
    "os": "mac", 
    "mac_version": "13.0.1", 
    "python_version": "3.10.0"
}
```

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — CHANGES_REQUESTED** [review]
LGTM, though is there a test we ca add to verify that these things are being stored?

**Comment by htahir1** [comment]
@schustmi I think the answer is both

**Comment by fa9r** [comment]
Okay then let's track both. Now we have `client_environment` as well as `orchestrator_environment`.

**Comment by htahir1** [comment]
I think canonically we call this environment `runner` not `client`. if you'd  like to change this wording please also search through the docs for the mention of the word runner

**Review by htahir1 — APPROVED** [review]
Apart from the runner/client comment above LGTM

**Comment by fa9r** [comment]
@htahir1 renamed "runner" to "client" in the docs (was only the vertex page actually)

**Comment by fa9r** [comment]
@strickvl I added an integration test that checks whether the post execution class has both environments correctly set. Also added a unit test for the new `get_run_environment_dict` function.

**Review by strickvl — APPROVED** [review]

**Review by schustmi — APPROVED** [review]

**Pull request merged**
