### PR TITLE
Copy huggingface data directory to local before loading in materializers

### PR DESCRIPTION
**Pull request by TimovNiedek**
## Describe changes

I fixed the huggingface materializers to achieve compatibility with Google Cloud Storage.

The previous implementation assumed that a pytorch/tensorflow model or a tokenizer could be loaded from the uri directly, which in this case is a path to a directory. As Google Cloud Storage uses a flat namespace, this is not supported, thus the files first need to be downloaded to a temporary directory before loading.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] ~If my change requires a change to docs, I have updated the documentation accordingly.~ does not apply
- [x] ~If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).~ does not apply
- [x] I have added tests to cover my changes. _--> the existing unit tests are sufficient in my opinion, but please let me know if you need me to add more_

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by strickvl** [comment]
Thanks for this contribution, @TimovNiedek! I'll let the test suite run and take a look at the code. I'm going to be working on another task relating to the HuggingFace example so this is nicely timed!

**Comment by TimovNiedek** [comment]
@strickvl it appears that there is one integration test failing for macos + 3.10, though I believe that test is unrelated to my changes. Please let me know if there's anything I can do!

**Comment by htahir1** [comment]
@TimovNiedek Yes the test seems inrelated. I'll update your branch with develop and see if it happens again - sometimes these are sporadic.

@strickvl WIll get back to you this week and we'll try to get this merged ahead of the next ZenML release. Thank you for the contribution!

**Review by strickvl — APPROVED** [review]
Looked this over properly and it all looks good to me. Thanks also for making all the fixes to satisfy `mypy` and so on. Appreciate the fact that you went the extra mile here!

**Pull request merged**
