### PR TITLE
Don't use pod resources/affinity for kubernetes orchestrator pod

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by AlexejPenner — COMMENTED** [review]
Can any of these values be set from the kubernetes orchestrator configuration? IF so are those removed through this change?

**Comment by schustmi** [comment]
The settings that get fetched (and that I override) already include the configuration of the stack component as well as any runtime settings that were provided as an override.

**Review by AlexejPenner — APPROVED** [review]
:seal:

**Comment by dragosmc** [comment]
Thanks for this feature as it makes sense not to use a huge instance that a step requires just to run the orchestrator. With this change, though, what's the way to specify pod_settings for the orchestrator? We still need to force it to run on specific nodes.

**Comment by AlexejPenner** [comment]
> Thanks for this feature as it makes sense not to use a huge instance that a step requires just to run the orchestrator. With this change, though, what's the way to specify pod_settings for the orchestrator? We still need to force it to run on specific nodes.

Thank you for raisin g your concern here, we've come up with a new way to do just that [here](https://github.com/zenml-io/zenml/pull/2732)

**Pull request merged**
