### PR TITLE
Update cheat sheet with latest CLI commands from 0.13.0

### PR DESCRIPTION
**Pull request by dnth**
## Describe changes
This PR updates the cheat sheet with latest CLI command breaking changes from 0.13.0.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/mlops-stacks/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Other (add details above)

### CODE REVIEW

**Comment by strickvl** [comment]
The big thing I see needing changing is the `zenml served-models...` command which no longer exists. It is now `zenml model-deployer models ...` for equivalent functionality. Also the following annotation commands:

```shell
zenml annotator up — Spin up the annotation server in the background

zenml annotator dataset list — List the datasets that are available to use in your annotation interface
zenml annotator dataset stats [DATASET_NAME] — Learn how much of your dataset you have labelled and how much remains
zenml annotator dataset annotate [DATASET_NAME] — Launch the annotation interface for a particular dataset
```

**Comment by strickvl** [comment]
Also might be worth waiting for Stefan's branch #865 to be merged in since that'll remove a section + add some new commands...

**Comment by strickvl** [comment]
Ok then keep the `profile` commands until that happens... That makes sense.

**Comment by fa9r** [comment]
Another thing to keep in mind for the next version: we also have a whole bunch of CLI commands related to user/permission management (project, user, team, role). Currently it makes sense that these are not on the cheat sheet since they are basically useless, but we might want to include some of them once the ZenServer is out.

**Comment by dnth** [comment]
@strickvl added annotation CLI :)

**Comment by strickvl** [comment]
@dnth wondering whether the headers for each command should be human-comprehensible headlines and not just the first part of the command? i.e. "Annotation" instead of `zenml annotator` etc? and 'Deployed Models' instead of `zenml model-deployer models`?

**Comment by strickvl** [comment]
@dnth looks great to me!

**Comment by dnth** [comment]
@strickvl Done! :fire:

**Review by strickvl — APPROVED** [review]

**Pull request merged**
