### PR TITLE
Rename nlp example

### PR DESCRIPTION
**Pull request by safoinme**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

## Summary by CodeRabbit

- **Refactor**
  - Renamed the directory for better clarity of the end-to-end natural language processing use case.
  - Updated workflow references to align with the new directory name.

### CODE REVIEW

**Comment by strickvl** [comment]
@coderabbitai review

**Comment by strickvl** [comment]
@safoinme wondering if it's maybe clearer to rename to just `e2e_nlp` without the `use_case` as part of the name? @htahir1 wdyt?

**Comment by htahir1** [comment]
Yes e2e_nlp is way better

**Review by htahir1 — APPROVED** [review]
Lets rename to e2e_nlp and also make changes to the template accordingly :-) Otherwise LGTM

**Review by htahir1 — CHANGES_REQUESTED** [review]
@safoinme another problem right now is that we dont materialize the option to deploy to sagemaker or HF here, but just locally, which isnt that  cool. can we materialize all the options?

**Pull request merged**
