### PR TITLE
Remove explicit nbconvert and markupsafe dependency

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/mlops-stacks/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
Wow markupsafe was so annoying, and im very happy to get rid of it. However, one second thought I am unsure why have nbconvert as a dependency in the first place?

**Review by htahir1 — COMMENTED** [review]
is this a deptree thing? What about getting rid of pyarrow?

**Comment by schustmi** [comment]
Yes deptree is a actually a really good idea, we'd just need to make sure we install all the integrations before running it (as from what I've seen this update here clashes not with the zenml installation, but only once we try to install mlflow).

Regarding pyarrow: 
This will break backwards compatability with previously saved artifacts, should we do it anyway?

**Comment by schustmi** [comment]
My findings on why the integration tests are failing for this PR:

On Windows: we're trying to install `markupsafe` in the virtual environment while it is currently imported.

On Linux: it's a combination of the integrations `airflow`, `neural_prophet` and `mlflow`
- The default installation of ZenML leaves us with `Jinja2==3.1.2` and `MarkupSafe==2.1.1`
- Installing airflow on top of that installs (among other things) `Jinja2==2.11.3`, `MarkupSafe==1.1.1` and `Flask==1.1.4`
- Installing neural prophet after that: `Jinja2==3.1.2`, `MarkupSafe==2.1.1` and`Flask==1.1.4`  ⚠️ This is now broken as the installed flask version requires older versions of jinja and markupsafe
- Installing mlflow after that: Downgrades `Jinja2==2.11.3` but the markupsafe version still doesn't match and leads to the import error in the tests

**Comment by schustmi** [comment]
Solved by #1042

**Pull request closed without merging**
