### PR TITLE
[ANALYTICS] Allow server to override client's analytics opt-in

### PR DESCRIPTION
**Pull request by wjayesh**
## Describe changes

We want the client analytics opt in to be overridden by the value from the server. This would allow more control over the analytics in the case of managed ZenML servers, both by ZenML and any other organization that creates and hosts them.

### Scope
One way of ensuring this use case is:
- as soon as a server is connected, we call the /info endpoint on the server and get the value for the analytics opt-in and update the client's global config.

### Challenges
- What happens if we change the value in the server after the client is connected?
**Solution:** Should we hit the /info endpoint periodically to check if the value has changed?
or can we ignore that case now, since the only use of this feature is in our managed servers and we will not be changing the value of the analytics opt in in the server, once it is set.

- The client can simply override the value in its global config again
**Solution:** One way of solving this would be to check the `gc.store.config.analytics_opt_in` value (if it is set) instead of the value in gc, everytime an analytics call gets made. This can be done in the `__init__` function of the `AnalyticsContext` class.

### Questions

- Should I be overriding the `get_store_info()` function on the `SQLZenStore` to return an analytics variable or should I enable this extra variable for all server types.
- Adding the this would mean more complexity as the user might expect the analytics opt-in value in the server to always reflect in the global config which in its current scope, it won't.
- Is the `RestZenStoreConfig` a good place to add the analytics opt in variable?

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
Apart from the failing tests, I would ask the question: How would this affect our analytics in Mixpanel? Would we now get 'server' events as well as client events, if both are opted in? i.e. will there be duplicate events? What ID would the server have

**Comment by wjayesh** [comment]
@htahir1 That's a good point. I added a new variable in the global config whose only purpose is to determine if the client analytics setting should be overridden. While creating the servers, we can now just set this to true to serve our use case. In this scenario, only the client-side analytics will be activated, and the server won't send any metrics like usual.
As for the tests, I'll get to them once this idea and implementation is validated..

**Comment by htahir1** [comment]
@wjayesh

> While creating the servers, we can now just set this to true to serve our use case. In this scenario, only the client-side analytics will be activated, and the server won't send any metrics like usual.

Do you mean when its set to false, only client-side analytics is activated?

**Comment by wjayesh** [comment]
@htahir1  Yes, when it is set to false, the client-side analytics will follow whatever value the user has set there. But when set to true, the server will override the client-side analytics opt-in value and set it to true.

**Comment by wjayesh** [comment]
Nope, we won't get double the metrics because the server-side analytics (decided by the value of `analytics_opt_in` in gc) is always set to false. The override is done based on the value of a new variable (`override_client_analytics_opt_in`) in the global config that has no relation to server-side analytics and only acts as a switch.

**Comment by htahir1** [comment]
I would like to see a demonstration of this with tests before we merge it if thats okay

**Comment by wjayesh** [comment]
Sure, I'll set some testing up and let you know.

**Pull request closed without merging**
