### PR TITLE
Define `@pipeline` and `@step` decorators as public API

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes

The pipeline and step decorators are now part of the public API and can be imported via `zenml.pipeline` and `zenml.step` directly.

### Detailed Changes
- moved both decorator definitions to a new `zenml.api` package
- adjusted `zenml.__init__.py` to import the decorators
- optimized imports so we don't need to import anything except for `typing` to load the decorators
- ~~adjusted all examples/... imports to use `from zenml import pipeline, step` syntax instead (thus all the file changes)~~

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — APPROVED** [review]
The core changes look good to me. Will look through the rest of the changes when they're re-reverted in case anything slips through, though testing should hopefully be the biggest barrier to pass with all that.

**Comment by fa9r** [comment]
@alex-zenml all the integration tests already passed before I reverted the example changes, so I think those should be good. IMO not worth reviewing even, looking over 250 files that all just do the same two import changes

**Review by schustmi — COMMENTED** [review]
I would highly suggest waiting with this until my new pipeline/step interface is merged. Reason for that is: At that point we will have multiple pipeline/step decorators (new and old for backwards compatibility) and we want to expose the new ones as our public API. However if we release this, we need to keep this backwards compatible and can't expose the new API here

**Comment by fa9r** [comment]
@schustmi I agree, we should certainly wait with merging this till the new interface is out.

The main point was to get early feedback on how/where we could define that API and how to make it fast

**Comment by schustmi** [comment]
What are the benefits of having it in a separate `api` module instead of just importing it in the root `__init__.py` directly?

But in general I'd love to have this, we should include even more classes though: `Client`, `StepContext`, `Output`, `ResourceSettings`, `DockerSettings`, `Schedule`, the post execution classes come to my mind

**Comment by fa9r** [comment]
> What are the benefits of having it in a separate api module instead of just importing it in the root __init__.py directly?

To keep imports as small as possible. E.g., for the `@pipeline` decorator, if we would keep it in `zenml.pipelines.pipeline_decorator` and just import it in the root `__init__.py`, then that would import everything that `pipelines.__init__.py` imports. 

So I saw three options how to handle this:
- move public api to a separate `api` module that is highly import optimized (current solution)
- define all the public api in the root `__init__.py` directly 
-> not maintainable as our API grows
- keep functions where they are and remove submodule imports (e.g. delete all the imports in `pipelines.__init__.py`) 
-> not backwards compatible since we have been using, e.g., `from zenml.pipelines import ...` for years in all our docs/examples/... now

**Comment by fa9r** [comment]
> When you import `from zenml.steps.step_decorator import step`

Yeah but if you import `from zenml import step` directly this will not import `zenml.steps` at all which is the main point

**Comment by fa9r** [comment]
> 



> When you import `from zenml.steps.step_decorator import step`, this one will also import the `zenml/steps/__init__.py` module

Exactly, that's why I moved it to `zenml.api.step_decorator`, now only `zenml/api/__init__.py` gets imported (which is empty)

**Pull request merged**
