### PR TITLE
Fix flaky CLI tests

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes

- Fixes the CLI server tests
- TODO: Fixes the docker prune fail during integration tests 

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by strickvl** [comment]
@schustmi I guess these are the same failing tests? https://github.com/zenml-io/zenml/actions/runs/4605709310/jobs/8143515643?pr=1462

**Comment by fa9r** [comment]
> @schustmi I guess these are the same failing tests? https://github.com/zenml-io/zenml/actions/runs/4605709310/jobs/8143515643?pr=1462

Nah I think these are unrelated. Maybe I fixed those in #1470. Let's see.

**Comment by fa9r** [comment]
@schustmi #1470 fixed the other issue, if you merge develop you can check whether all tests now pass on your branch

**Review by fa9r — APPROVED** [review]
Let's go to main 🚀 🚀 🚀

**Pull request merged**
