### PR TITLE
Cleaning up the assets pushed by gitbook automatically

### PR DESCRIPTION
**Pull request by bcdurak**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Removed the assets added by gitbook
There was a single link to a such file which is now fixed

### CODE REVIEW

**Review by AlexejPenner — APPROVED** [review]
:broom: :fire:

**Review by htahir1 — APPROVED** [review]
LGTM! Thanks Baris!

**Review by alex-zenml — APPROVED** [review]
Thanks! Do we know why they got generated, @bcdurak? Does this happen every time we create a version or is this just legacy assets?

**Comment by bcdurak** [comment]
@alex-zenml The commit history shows that @htahir1 had a few changes in the last few days however I am not sure. Considering that there was already a link to one of the images added by gitbook, my guess is, the docs must have been changed through gitbook by mistake.

**Comment by htahir1** [comment]
It might be auto generated from gitbook but lets keep an eye on it if it happens again

**Pull request merged**
