### PR TITLE
add jayesh to the team

### PR DESCRIPTION
**Pull request by wjayesh**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Briefly describe the changes you have introduced.

### CODE REVIEW

**Comment by wjayesh** [comment]
I'm not sure how the other 3 commits ended up in my PR but I'll try to find out

**Comment by htahir1** [comment]
@wjayesh Did you first try to to PR to `main` and then changed it to `develop`?

**Comment by htahir1** [comment]
I think you might have branched off of the wrong branch then in this case. Try and create a fresh branch off of `develop` and maybe create a new PR?

**Comment by wjayesh** [comment]
sounds good, hamza

**Pull request closed without merging**
