### PR TITLE
Fix bug in HyperAI orchestrator depends_on parallelism

### PR DESCRIPTION
**Pull request by christianversloot**
## Describe changes
There is a newly discovered issue with the HyperAI orchestrator which leads to unexpected behavior when a step depends on multiple previous steps. Upon investigation a bug was identified as currently the `depends_on` dict that eventually leads to the Docker Compose file is overwritten for every step a downstream one is dependent on. This PR fixes the issue by first initializing the dict to an empty one if it discovers that a step is dependent on others; then adds them one by one by updating it. I have just tested locally with the following Compose file, and multi-container dependency works nicely, so the fix also works Docker side.

```
version: '3.8'
services:
  hello-world:
    image: busybox
    command: /bin/sh -c "sleep 30"
  hello-world2:
    image: hello-world
  hello-world3:
    image: hello-world
    depends_on:
      hello-world:
        condition: service_completed_successfully
      hello-world2:
        condition: service_completed_successfully
```

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [x] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by avishniakov — APPROVED** [review]

**Review by schustmi — APPROVED** [review]

**Comment by strickvl** [comment]
@christianversloot could you run the formatting script? Otherwise this looks good to go.

**Comment by christianversloot** [comment]
@strickvl absolutely, had already done so, but realized it used an older `ruff` version. Noticed in the pipeline that `ruff==0.3.2` is used, so I've now formatted with that version. If you could launch the pipeline, that would be great.

**Comment by strickvl** [comment]
Yeah we now just use whatever latest and greatest `ruff` is, same with `uv`, coupled with more specific opt-in rule sets so we don't get surprised by whatever newness they add support for.

**Comment by christianversloot** [comment]
@strickvl in the pipelines, when using `uv`, what are the performance gains you're seeing?

**Comment by christianversloot** [comment]
@strickvl Interesting! If I don't forget I will try it as soon as the new version is published :)

**Pull request merged**
