### PR TITLE
Ensure `rich` CLI displays full text and wraps table text

### PR DESCRIPTION
**Pull request by strickvl**
## Describe changes
I've solved the issue were `rich` was shortening text inside tables. Also, the text of almost all the contents of these tables should now be accessible as a 'link', so if your terminal supports in-terminal links (by holding down CTRL or CMD, i.e.) then users will be able to do that to copy the text inside a specific cell.

The one caveat that doesn't work right now is when a cell's text contains a space. So far, the two things this affects is JSON values and path values coming from Mac or Windows environments (both of which often have spaces). It wouldn't be trivial to solve and for those two specific items there isn't a great deal lost in not being able to click-select them as a link. They *will* still all be visible and behave like the rest of the tables in terms of wrapping as columns.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by htahir1** [comment]
I still get this when I use the branch on Windows WSL. I am unable to click using the new Windows Terminal application, even though im sure its capable to support link clicks

image

**Comment by htahir1** [comment]
@strickvl  Cool!
image

Ok now it seems to work but Cntrl+Copy on the links gives me this error.. I think that interpreting these as links does not really make sense as then the terminal wants to open it as a link in the browser

**Comment by strickvl** [comment]
@htahir1 It's the only way to allow users to access the details of a cell when it wraps to a new line, unfortunately. I found that CTRL-clicking and copying, and then pasting it, worked for me.

Happy to brainstorm other suggestions, but this seems to be the only way with `rich`.

**Review by schustmi — APPROVED** [review]
LGTM!

**Pull request merged**
