### PR TITLE
Add `mlstacks` compatibility check to CI

### PR DESCRIPTION
**Pull request by strickvl**
I added a check for the `zenml` release workflow which checks that the current package (editable install on the release branch) can be installed in the same environment as `mlstacks`.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by safoinme — APPROVED** [review]

**Comment by strickvl** [comment]
> How critically does `zenml` rely on `mlstacks`? Do we want this CI check just to inform us or actually it's a hard requirement before releasing

That's a good question. If you can't install the two in the same environment then you can't use `zenml stack deploy...` etc, so I'd say if `mlstacks` is a core part of the ZenML flow / functionality then it should be a hard requirement.

But open to other opinions...

**Review by avishniakov — COMMENTED** [review]
Hm, I have a feeling that we better catch it earlier rather than on release... Here it is too late to make fixes, so why we not include this as part of regular CI as well?

**Comment by strickvl** [comment]
@avishniakov yeah can do. It doesn't add much in terms of time. I'll update.

**Review by fa9r — APPROVED** [review]
Cool, great idea 🙌

**Pull request merged**
