### PR TITLE
GCP Image Builder network 

### PR DESCRIPTION
**Pull request by gabrielmbmb**
## Describe changes

I encountered an authentication problem while trying to build a pipeline Docker image that uses a dependency from a private GCP Artifact Registry using the GCP Image Builder.

As described in this [Google Cloud documentation page](https://cloud.google.com/build/docs/build-config-file-schema#network) about Google Cloud Build, when cloud build runs a step the container gets attached to a network called `cloudbuild` that can be used to get the Application Default Credentials.

In order to install a dependency from a private GCP Artifact Registry, the build container needs to be attached to this network using `--network=cloudbuild` option. This way, the container will be automatically authenticated and the dependency can be installed from the private GCP Artifact Registry. For it to work, you will also need to use a custom base `Dockerimage` like this one:

```dockerfile
FROM zenmldocker/zenml:0.33.0-py3.10

RUN pip install keyrings.google-artifactregistry-auth
```

This PR adds the `GCPImageBuilder.network` attribute that can be used to pass the name of the network to which the build container has to be attached. By default, I gave it the value of `cloudbuild` as it's likely that someone building a Dockerimage using the Google Cloud Build will need to install a dependency from a private GCP Artifact Registry.

Let me know if the instructions described above need to be included in the docs!

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by schustmi — COMMENTED** [review]
Code looks good to me! I don't think this needs an explicit mention in the docs, but maybe in the docstring of the `network` attribute we could add the link to the google docs page that you also linked in the PR?

**Comment by gabrielmbmb** [comment]
What about the base `Dockerfile` that is needed with the `keyrings.google-artifactregistry-auth` dependency? Should we mention it in the GCP Image Builder documentation page as a caveat?

**Comment by schustmi** [comment]
@gabrielmbmb Good point, seems like that isn't mentioned anywhere on their page and would be helpful for our users

**Comment by gabrielmbmb** [comment]
@schustmi I've added it to the GCP Image Builder documentation page

**Review by schustmi — APPROVED** [review]
Thanks so much, will merge once the checks pass!

**Pull request merged**
