### PR TITLE
Improve detection of third party modules during class resolving

### PR DESCRIPTION
**Pull request by schustmi**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
- Detect whether a module belongs to a third party package when resolving a class

### CODE REVIEW

**Review by htahir1 — CHANGES_REQUESTED** [review]
Cool! Can we add some tests to this to make sure it works as intended?

**Comment by schustmi** [comment]
I thought about it but found some problems, maybe you have a suggestion on how to avoid them:
In order to test this, we would need to
- create a virtual environment inside the git/zenml repository
- run `poetry install` inside this virtual environment
- delete the virtual environment

Especially the installation step would take far too long in my opinion, wdyt?

**Comment by htahir1** [comment]
Won't we already have some sitepackages inside the testing env? Is there a sitepackage we can leverage for it that happens to be installed anyway?

**Comment by schustmi** [comment]
Yes but they will not be inside this git repository I believe? And even if it was, to test both ways we would need one virtualenv that's inside the git repository and another one that is outside anyway I think

**Comment by schustmi** [comment]
So I guess we could detect whether the function detects a third party module (but not the actual case for the bug which was a virtualenv inside the repo)

**Comment by htahir1** [comment]
Ok yeah you're right, its too much overhead. But we should at least try that it works locally? We should check once before merging :-)

**Comment by schustmi** [comment]
@htahir1 Added a small test for the simple detection of third party modules now. I tested it locally for me with virtual environments both inside and outside the git repository, but would be nice if you could run it on your machine as well :)

**Review by htahir1 — APPROVED** [review]
Works for me locally too! Great job

**Pull request merged**
