### PR TITLE
Fix/update `zenml go`

### PR DESCRIPTION
**Pull request by strickvl**
- I fixed some text display / formatting issues
- I sorted the order in which the notebook titles are displayed so that they're alphabetically ordered
- I added a 'press enter to continue' prompt so the user doesn't get immediately plunged into jupyter notebook CLI garbled output + so they can actually read what we wrote.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — APPROVED** [review]
I like it. Can you change the base branch to be `doc/hamza-misc-updates`? Otherwise we get clashes

**Review by AlexejPenner — APPROVED** [review]
LGTM - changed base branch for you, there seems to be some conflict.

**Comment by htahir1** [comment]
Conflict came from my branch, now fixed it in my branch, that has removed the conflict also from this one :-)

**Comment by strickvl** [comment]
@htahir1 @AlexejPenner should / may I merge this now? I don't fully understand what happened in the intervening comments :)

**Pull request merged**
