### PR TITLE
Prepare release 0.68.0

### PR DESCRIPTION
**Pull request by bcdurak**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by schustmi** [comment]
@bcdurak Some things are missing I think 🤔

**Comment by bcdurak** [comment]
No, no. That's the first issue that I bumped into. Normally, we wanted to trigger the workflow when the PR gets created. But, since I automated everything, the releaser does not have to make any changes, but without any changes you can not open up a PR 😄

**Comment by bcdurak** [comment]
@schustmi Also, we can not trigger the workflows on `pull_request.opened` since they are not on `main` yet. Any ideas?

**Comment by schustmi** [comment]
Ah I thought this was already the automatically created PR, nvm then

**Review by schustmi — APPROVED** [review]

**Comment by schustmi** [comment]
> @schustmi Also, we can not trigger the workflows on `pull_request.opened` since they are not on `main` yet. Any ideas?

Merge them to main? 😄

**Comment by bcdurak** [comment]
@schustmi Closing this as the triggers for the workflows have changed.

**Pull request closed without merging**
