### PR TITLE
Enable accessing the metadata store through the step context

### PR DESCRIPTION
**Pull request by schustmi**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
- Enable accessing the metadata store through the step context
- Modify kubeflow metadata store to switch connection config depending on the environment

### CODE REVIEW

**Comment by schustmi** [comment]
I have a suggestion for a feature that we might add to this PR: Should we somehow "disable" (= raise an Exception) if the users access the `Repository` during a step function now that we provide the option to get it via the `StepContext`?

**Review by htahir1 — COMMENTED** [review]
I have one comment and one question:

Comment: How about renaming the `step_context` to `fetch_historical_runs` or something?
Question: Why do we need to change the Kubeflow metadata config based on env?

Other than that it LGTM

**Comment by schustmi** [comment]
@htahir1 Definitely like the "fetch_historical_runs" name, I'll change that. 
Regarding your question: We need to differentiate how to access the KFP internal database depending on if we're inside a KFP pod or not. If we're outside, we treat it as an ordinary MySQL database (this additionally requires a `kubectl port-forward` to work). When inside the pod, KFP takes care of making sure the database is reachable at a certain host/port and we connect to the database this way. Previously this distinction was implemented inside the `zenml.integrations.kubeflow.container_entrypoint.py` (see the removed lines there which handle if it's a `KubeflowMetadataStore` or not), but this meant that the actual `KubeflowMetadataStore` class wasn't usable inside KFP pods.

Do you have an opinion on my previous comment on this PR?

**Comment by htahir1** [comment]
Ah makes sense! Regarding your suggestion: maybe we can add that as an additional ticket in the board and reprioritize that accordingly. Not sure if its big enough of a deal to implement now

**Comment by schustmi** [comment]
Makes sense, I added a ticket for that!

**Pull request merged**
