### PR TITLE
RAG guide for docs

### PR DESCRIPTION
**Pull request by strickvl**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — CHANGES_REQUESTED** [review]
Here is some feedback:

* Feels like you can slim it down a bit, comes across slightly wordy and less code than it should be? -> Maybe Tracking RAG-associated artifacts seems like a chapter that could either be integrated into other chapters as a section or could do with more examples
* I think we need a small note here or there to talk about to run these pipelines locally or in a remote stack where we can scale up GPU and CPU .. not sure where it fits but i think it could be a nice addition
* For the RAG inference pipeline i don quite get it as it isnt really a pipeline is it? I dont get it from the code snippet as it uses a lot of functions id like to understand
* In terms of the code itself, i think every chapter should have a call out and link to the right section of the code. Sometimes people skip chapters and want to see the code immedietely , so a link after every code snippet might be a nice addition
* lastly, see image, link isnt formatted properly

image

**Review by htahir1 — APPROVED** [review]
image

This image is pixelated here: https://zenml-io.gitbook.io/alextestingground/Z1RNwxFe5UgX8V1GrZoR/user-guide/llmops-guide/rag-with-zenml/storing-embeddings-in-a-vector-database

apart from that I love it! 

My only criticism is that the front is too 'text-heavy', a lot of words to read before the action shows up. Might make sense to have a small example to run at the very start to make developers excited? 

Generally, I would merge and backport this first and then do the improvements

**Comment by strickvl** [comment]
@htahir1 Pixellation is on purpose, to remove reference to my supabase org / db name etc. I will merge this in now, backport and then see what I can do about making it less text-heavy.

Note there's lots of reference to the project itself, which would probably want to be merged in before I do the full backport merge. There's an open PR here https://github.com/zenml-io/zenml-projects/pull/97

**Comment by strickvl** [comment]
Oh I guess you maybe mean that the image could be higher quality... I can bump that a bit for sure...

**Pull request merged**
