### PR TITLE
Make terraform an optional dependency

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes
This PR removes `python-terraform` as a required dependency and makes it available as an extra instead.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by AlexejPenner — APPROVED** [review]
LGTM - did you manually verify that the stack recipes all still work with the larger changes of moving code around? If I am not mistaken, we don't really have good test coverage of these functions.

@wjayesh I think your review is definitely needed here.

**Review by htahir1 — CHANGES_REQUESTED** [review]
We should at least update the docs and examples in this PR that are affected and not let the exception manage it

**Review by wjayesh — APPROVED** [review]
Thank you for not just removing python_terraform as permanent dependency but also structuring the classes into logical files. It looks much cleaner now, LGTM!
P.S. I verified that the deploy still works.

**Comment by strickvl** [comment]
@schustmi is this still planned for after mlstacks happens? I didn't remove the logic for `zenml deploy` so there's still a lot of the 'old way' still inside the codebase.

**Comment by fa9r** [comment]
Closing in favor of #1855

**Pull request closed without merging**
