### PR TITLE
Replacing lingering references to metadata store

### PR DESCRIPTION
**Pull request by htahir1**
## Describe changes
I took out some lingering metadata store references but some are left over and some README's need an update

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by htahir1** [comment]
@wjayesh  and @safoinme I notice that the whole KServe, custom deployment, and seldon README's are  very verbose and might need a simpler neater alternative! :-) Is it possible that you guys help me re-write them?

**Review by safoinme — APPROVED** [review]
LGTM!
@htahir1 should the examples contain the remote ZenML Server deployment section just like in the Blog?

**Review by schustmi — APPROVED** [review]

**Comment by htahir1** [comment]
@safoinme I think so yes!

**Comment by schustmi** [comment]
@htahir1 can we merge this?

**Comment by htahir1** [comment]
Closing in favor with @bcdurak 's upcoming PR

**Pull request closed without merging**
