### PR TITLE
Load artifact store before loading artifact to register filesystem

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by safoinme — APPROVED** [review]

**Review by htahir1 — COMMENTED** [review]
@schustmi Would you mind adding a note in the docs about the behavior Jiri experienced on the slack thread as well? https://zenml.slack.com/archives/C01FWQ5D0TT/p1677661528488819?thread_ts=1677596537.697169&cid=C01FWQ5D0TT

**Comment by schustmi** [comment]
@htahir1 This PR fixes that issue, what would you additionally expect in the docs?

**Comment by htahir1** [comment]
@schustmi I thought maybe if there is a way to still get this error it might make sense to talk about managing multiple active stacks and how it affects the post execution workflow, But if thats sovled feel free to merge

**Comment by schustmi** [comment]
I think this completely eliminates that tbh, as we always load the correct artifact store now in which the artifact is stored. The only issue is if they somehow deleted the artifact store, but at that point there's also nothing we can do to help them (we can't simply activate a random artifact store and hope it works)

**Comment by htahir1** [comment]
I think the real question I have is: Why does reading the artifact from the artifact store require you to activate the right stack in the first place in post-execution? Isnt that something ZenML should figure out

**Comment by schustmi** [comment]
But isn't this exactly what this PR is implementing? Yes I agree ZenML should figure this out. This PR implements the figuring it out. It needs to load the artifact store to register the filesystem with the correct credentials to access the e.g. S3 bucket?

Btw this PR doesn't activate any stack, it simply loads the artifact store (= registers the file system with the configured credentials) that was used to store the artifact. We're not storing the credentials and source code of the filesystem for every artifact, so I don't see any way around that.

**Comment by htahir1** [comment]
Ok now i understood it! Sorry! LGTM

**Pull request merged**
