### PR TITLE
Set contains_code to 1 instead of True

### PR DESCRIPTION
**Pull request by kobiche**
## Describe changes
To allow compatibility to older versions of sqlite3 (<3.23), I'd suggest setting the contains_code column to 1 instead of True

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
WIll this have implications on current deployments of ZenML (backwards compatability?)

**Comment by htahir1** [comment]
Okay can you rebase your changes on to the develop branch, rather than main. Ill get some reviewers in the meanwhile

**Comment by schustmi** [comment]
@htahir1 Same for MySQL, and users with existing DBs will not re-run this migration and are therefore not impacted at all anyway.

**Comment by kobiche** [comment]
I'll create a new PR since I cannot rebase the origin branch _develop_ into my patch branch without messing with the commit history. 
New one is #1685

**Pull request closed without merging**
