### PR TITLE
Deprecate KServe Integration

### PR DESCRIPTION
**Pull request by fa9r**
## Describe changes
Deprecate the KServe integration since it is no longer maintained, by:
- Adding a deprecation warning to the KServe model deployer
- Removing KServe examples/docs 

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

### CODE REVIEW

**Review by strickvl — CHANGES_REQUESTED** [review]
The kserve example will also need a warning, as will the relevant parts of `custom_code_deployment` example.

**Comment by strickvl** [comment]
Also these pages will need updating:

- https://zenml.io/integrations/kserve
- https://blog.zenml.io/deploy-with-kserve/

To reflect the deprecation.

**Comment by schustmi** [comment]
I'm wondering if we should even get rid of the example/docs page entirely as to not bring more visibility to the integration if it will be removed in the future? Or is the plan to keep the integration but not maintain it anymore?

**Review by safoinme — APPROVED** [review]
Good Bye Kserve!!

**Review by strickvl — APPROVED** [review]

**Review by schustmi — APPROVED** [review]

**Pull request merged**
