### PR TITLE
Add test for registration of integration stack components

### PR DESCRIPTION
**Pull request by schustmi**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Add test for registration of integration stack components

### CODE REVIEW

**Review by htahir1 — APPROVED** [review]
Beautiful PR. I was going to ask you whether we could avoid the noqa in the future :-)! Also loved that you snuck in the GItHub Action refactor!

**Review by alex-zenml — APPROVED** [review]
🙏🏻

**Comment by htahir1** [comment]
The tool to debug it is tmate and you can find a usage of it here: https://github.com/tiangolo/sqlmodel/blob/main/.github/workflows/publish.yml

**Comment by schustmi** [comment]
@htahir1 Thanks!

**Pull request closed without merging**
