### PR TITLE
Produce periodic mocked data for Segment/Mixpanel

### PR DESCRIPTION
**Pull request by AlexejPenner**
## Describe changes
This branch is meant to create a test script to verify our North Star Metrics and Telemetry by posting events through segment to mixpanel.

The Dev_Segment_Key is imported and a arbitrary selection of metadata is sent along with the event itself. During testing two of the metadata fields are purposely set to:

'environment': 'gh_action_test'

In order to make it easier to filter these out with out normal filters of 'environment' == 'native' 

Within this script we have 3 classes of users. 
Daily users, weekly users and monthly users that post with different frequencies.

The Github action runs every day at 5:30 and sends 4 pipeline runs for the relevant users.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
This is cool. Will it start working when its on develop?

**Comment by AlexejPenner** [comment]
> This is cool. Will it start working when its on develop?

No only once its on main - currently I am trying to trigger the run at least once, then it will show up in the UI and can be triggered manually every day

**Comment by AlexejPenner** [comment]
Ready to rumble - the github action posted its events to the DEV mixpanel - we can now trigger it manually every day until the next release. Will finalize everything and un-draft-ify this Pr

**Review by htahir1 — APPROVED** [review]
LGTM!

**Pull request merged**
