### PR TITLE
Repeated Paragraph in the documentation for core-concepts

### LINKED ISSUE #316: Repeated Paragraph in the documentation for `core-concepts`
In the file `core-concepts.md`, the section on [`Pipeline`](https://github.com/zenml-io/zenml/blob/b94dff83f0e7c8ab29e99d6b42a0c906a3512b63/docs/book/introduction/core-concepts.md?plain=1#L27-L41) includes a repeated paragraph. The first paragraph in the the pipeline section is repeated in the 3rd paragraph of the same section.  

```markdown
Within your repository, you will have one or more pipelines as part of your experimentation workflow. A ZenML 
pipeline is a sequence of tasks that execute in a specific order and yield artifacts. The artifacts are stored 
within the artifact store and indexed via the metadata store. Each individual task within a pipeline is known as a 
step. The standard pipelines within ZenML are designed to have easy interfaces to add pre-decided steps, with the 
order also pre-decided. Other sorts of pipelines can be created as well from scratch.

Pipelines are designed as simple functions. They are created by using decorators appropriate to the specific use case 
you have. The moment it is `run`, a pipeline is compiled and passed directly to the orchestrator, to be run in the 
orchestrator environment.

Within your repository, you will have one or more pipelines as part of your experimentation workflow. A ZenML 
pipeline is a sequence of tasks that execute in a specific order and yield artifacts. The artifacts are stored 
within the artifact store and indexed via the metadata store. Each individual task within a pipeline is known as a 
step. The standard pipelines (like `TrainingPipeline`) within ZenML are designed to have easy interfaces to add 
pre-decided steps, with the order also pre-decided. Other sorts of pipelines can be created as well from scratch.
```

### PR DESCRIPTION
**Pull request by bhattbhuwan13**
The commit removes a repeated paragraph in the `Pipeline` section inside `core-concepts.md`

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Briefly describe the changes you have introduced.

### CODE REVIEW

**Comment by alex-zenml** [comment]
Thank you for this contribution, @bhattbhuwan13! You're completely right, and I appreciate that you took the time to make this fix.

**Review by alex-zenml — COMMENTED** [review]
This looks good to me, @htahir1, though I'm not sure if we want to merge into `main` or into `develop` under the new workflow.

**Comment by htahir1** [comment]
I think we should merge to `develop` and i changed it accordingly. Also LGTM!

**Review by alex-zenml — APPROVED** [review]

**Comment by bhattbhuwan13** [comment]
Hey @alex-zenml , mention not. I looked at the files changed and interestingly there were two files that were modified. I only modified the markdown file but it looks like a python file was also changed. How can that happen?
Screen Shot 2022-01-17 at 11 02 35 PM

**Comment by alex-zenml** [comment]
I think our automatic Jira parser made that change on its own. I'm not exactly sure why it ended up in this commit, however. (Any ideas, @schustmi?). In any case, don't worry about it. All seems well.

**Comment by schustmi** [comment]
Must have been something that the todo parser missed or that wasn't merged to develop yet, but as Alex already mentioned no worries at all

**Pull request merged**
