### PR TITLE
Fix broken links in quickstart and core concepts

### PR DESCRIPTION
**Pull request by wjayesh**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes

Fixed a few links in the documentation.

### CODE REVIEW

**Comment by htahir1** [comment]
@wjayesh You should probably merge develop into it and then try again assuming the evidently bug is fixed on develop

**Comment by bcdurak** [comment]
Besides the `evidently` bug, looks good to me as well! Good catch 👍

**Review by bcdurak — APPROVED** [review]

**Comment by schustmi** [comment]
How about we just merge it, this doesn't touch any code that could in any way lead to failing tests?

**Comment by wjayesh** [comment]
> Good catch! I am running the websites through some tools to make sure we catch all of these automatically. We should try do come up with a strategy for this

sounds good. automating this would be best

**Comment by alex-zenml** [comment]
I looked into automating it in the past. A big problem is that (because we break lines based on line-length) there are a quite large / not insignificant number of links that aren't actually broken, but they're just partial links.

There are lots of tools available, but we'll have a huge exception list if we want to automate this all. Not breaking based on line-length would make this much easier to address.

**Comment by jwwwb** [comment]
This should also be labeled "internal", right? Did the auto labeler not do its work?

**Comment by alex-zenml** [comment]
@jwwwb I think the issues is that @wjayesh has not yet been added to the `teams.yaml` file. @wjayesh you should add yourself to [this file](https://github.com/zenml-io/zenml/blob/main/.github/teams.yml). I'm not sure which branch to do so on. (@htahir1?)

**Comment by wjayesh** [comment]
@alex-zenml @htahir1 I have added it in the `develop` branch.

**Pull request merged**
