### PR TITLE
Made it so that fs = gcsfs.GCSFileSystem is not-instantiated in the c…

### PR DESCRIPTION
**Pull request by htahir1**
…lass variable scope to avoid compute engine metadata connections

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Briefly describe the changes you have introduced.
Made it so that fs = gcsfs.GCSFileSystem is not-instantiated in the c…

### CODE REVIEW

**Comment by schustmi** [comment]
Haven't tested anything, but won't it send 3 requests now anytime the filesystem is actually used?
Maybe some kind of lazily instantiating it, but just once would be nicer?

**Comment by htahir1** [comment]
Yes it would now make that connection each time. I was just making a short-term fix tbh - the real way is lazy loading it but I couldnt figure out the right time to do it. It should not be when the class is imported because then the connection happens each time zenml runs

**Comment by schustmi** [comment]
What about the first time the FS gets accessed? Could stay a class variable but it's `None` initially and gets set once the first method on the FS is called?

**Comment by htahir1** [comment]
@bcdurak Now takes over this PR in his branch after our discussion. He will implement something along the lines of what you suggest @schustmi. I will close the PR now :-)

**Pull request closed without merging**
