### PR TITLE
Allow configuration of s3fs

### PR DESCRIPTION
**Pull request by schustmi**
## Describe changes
This PR enables configuration of the `S3ArtifactStore` so users can connect to non-AWS S3 storage. To enable that, all artifact store methods needed to be converted to instance methods.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Comment by schustmi** [comment]
I have a few questions myself regarding this PR:
- @AlexejPenner Do you think it makes sense to write the documentation for this directly on your branch in the `ArtifactStore` section instead of having to copy/merge it from here or should I try to find a suitable place in the current docs?
- @bcdurak I seem to remember we talked about deregistering a filesystem from the tfx registry before. In theory after this PR there could be the following problem: A user runs on `S3ArtifactStore_1` which requires some custom configuration, then in the same python process they switch the active stack to a different `S3ArtifactStore_2` which will now be ignored as that file prefix is already registered. I see this as highly unlikely, but I imagine it wouldn't be too complicated to deregister an existing filesystem. What do you think, is this something we should implement in this PR?

**Comment by AlexejPenner** [comment]
> I have a few questions myself regarding this PR:
> 
> * @AlexejPenner Do you think it makes sense to write the documentation for this directly on your branch in the `ArtifactStore` section instead of having to copy/merge it from here or should I try to find a suitable place in the current docs?
> * @bcdurak I seem to remember we talked about deregistering a filesystem from the tfx registry before. In theory after this PR there could be the following problem: A user runs on `S3ArtifactStore_1` which requires some custom configuration, then in the same python process they switch the active stack to a different `S3ArtifactStore_2` which will now be ignored as that file prefix is already registered. I see this as highly unlikely, but I imagine it wouldn't be too complicated to deregister an existing filesystem. What do you think, is this something we should implement in this PR?

Probably makes sense to write it directly in the new docs :)

**Comment by bcdurak** [comment]
@schustmi You are absolutely right. I am not even sure which filesystem would be active at that moment. As far as I understand, there can be two filesystems in that registry for the same prefix, but the deciding factor is the priority that we set within the _register function. As they would have the same priority as well, I am not sure which one would be used. But as you said, this is very unlikely. In order for this to happen, they would actually have to create the instances of these stack components. However, if we try to cover this, would you think it would possible to manipulate the priorities within the registry to make sure that the active artifact store has the highest priority?

**Review by bcdurak — APPROVED** [review]
Everything looks good! Great changes.

**Pull request merged**
