### PR TITLE
Run KFP container as local user/group if local

### PR DESCRIPTION
**Pull request by stefannica**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Some files and folders in the local repositories (e.g. database,
.system TFX directories) are shared between different runs of the
same pipeline or of different pipelines. If pipelines are run
in the context of different users, such as when switching between
KFP and the local orchestrators, this can create problems with
permissions.

Running the KFP containers with the same UID/GID as the local
user maintains permissions consistent across orchestrators.

### CODE REVIEW

**Review by schustmi — COMMENTED** [review]
Looks good to me, just one question: Do you know if the bug also happened on windows in some form? Or do they just not care about any permissions and it already worked before this PR?

**Comment by stefannica** [comment]
> Looks good to me, just one question: Do you know if the bug also happened on windows in some form? Or do they just not care about any permissions and it already worked before this PR?

I don't think we even support KFP as a local orchestrator on Windows, but even if we did, the Windows host should ignore file permissions set on the KFP side.

**Review by AlexejPenner — APPROVED** [review]
lgtm, it might be worth checking out how it behaves on windows though

**Comment by bcdurak** [comment]
looks good to me as well!

**Review by bcdurak — APPROVED** [review]

**Review by schustmi — APPROVED** [review]

**Pull request merged**
