### PR TITLE
Always keep link to API docs pointed at the version of the release branch

### PR DESCRIPTION
**Pull request by AlexejPenner**
## Describe changes
I implemented a hacky github action that runs whenever somebody pushes to a release branch. The script extracts the version number from the branch name and then goes trhough the toc of the docs and edits all places where the api docs are referenced. 

If the toc has changes after this, the codemonkey account adds a commit onto the release branch with the updated links.

I have manually tested the last part of it on my local machine. The following scenarios work:

1) ` https://apidocs.zenml.io ` -> `https://sdkdocs.zenml.io/$VERSION ` 
2) ` https://apidocs.zenml.io/ ` -> `https://sdkdocs.zenml.io/$VERSION ` 
3) ` https://apidocs.zenml.io/1.2.3 ` -> `https://sdkdocs.zenml.io/$VERSION ` 
4) ` https://apidocs.zenml.io/1.2.3/ ` -> `https://sdkdocs.zenml.io/$VERSION/ ` 
5) ` https://apidocs.zenml.io/latest/ ` -> `https://sdkdocs.zenml.io/$VERSION/ ` 

1) ` https://sdkdocs.zenml.io ` -> `https://sdkdocs.zenml.io/$VERSION ` 
2) ` https://sdkdocs.zenml.io/ ` -> `https://sdkdocs.zenml.io/$VERSION ` 
3) ` https://sdkdocs.zenml.io/1.2.3 ` -> `https://sdkdocs.zenml.io/$VERSION ` 
4) ` https://sdkdocs.zenml.io/1.2.3/ ` -> `https://sdkdocs.zenml.io/$VERSION/ ` 
5) ` https://sdkdocs.zenml.io/latest/ ` -> `https://sdkdocs.zenml.io/$VERSION/ ` 

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by stefannica — COMMENTED** [review]
The github action looks good, but I have a couple of questions:

1. doesn't this create an infinite loop ? A github action triggered by commits to a branch that pushes a commit to the same branch.
2. this github action only updates the toc.md file, but what about the rest of `https://apidocs.zenml.io/latest` occurrences in the doc files ? Shouldn't those be updated as well ?

**Comment by AlexejPenner** [comment]
> The github action looks good, but I have a couple of questions:
> 
> 1. doesn't this create an infinite loop ? A github action triggered by commits to a branch that pushes a commit to the same branch.
> 2. this github action only updates the toc.md file, but what about the rest of `https://apidocs.zenml.io/latest` occurrences in the doc files ? Shouldn't those be updated as well ?

1)  If everything works as intended, then the second time the action is triggered, the file will not be changed, so the diff will be none and the commit will not be registered/pushed.
2) I'll check if there is any occurences

**Review by stefannica — APPROVED** [review]

**Comment by stefannica** [comment]
> > 2. this github action only updates the toc.md file, but what about the rest of `https://apidocs.zenml.io/latest` occurrences in the doc files ? Shouldn't those be updated as well ?
> 
> 2. I'll check if there is any occurences

I'd say there are plenty :smile: 
Screenshot from 2023-07-03 09-43-39

**Comment by AlexejPenner** [comment]
> > > 2. this github action only updates the toc.md file, but what about the rest of `https://apidocs.zenml.io/latest` occurrences in the doc files ? Shouldn't those be updated as well ?
> > 
> > 
> > 
> > 2. I'll check if there is any occurences
> 
> I'd say there are plenty 😄 Screenshot from 2023-07-03 09-43-39

Ah I left them there with the assumption that the gh action will take care of it, thus giving us proof that everything worked properly with our next release. As Its difficult to test gh action before they hit main, this seemed like an appropriate trial to me.

**Comment by AlexejPenner** [comment]
I ended up all those occurences of apidoc to sdkdoc after all, the /latest/ protion of the url should I show that it works on its own

**Pull request merged**
