### PR TITLE
Fixing the listing functionality of several objects in our CLI

### PR DESCRIPTION
**Pull request by bcdurak**
## Describe changes

This PR applies changes to the `zenml stack list`, `zenml stack-component list`, `zenml service-connector list`, and any function which uses the `print_pydantic_models` utility function such as `users` and `workspaces`.

With the new changes, if there is an active model in the overall list, **AND THERE IS NO FILTERING OR SORTING**, this object will always get appended to the top of the list. For instance, if you have 100 stacks and the active stack is stack number 51, you will get the following responses:

Example with `zenml stack list`:

```
┏━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━┓
┃ ACTIVE │ STACK NAME │ STACK ID                             │ SHARED │ OWNER   │ ARTIFACT_STORE │ ORCHESTRATOR ┃
┠────────┼────────────┼──────────────────────────────────────┼────────┼─────────┼────────────────┼──────────────┨
┃   👉   │ stack_51   │ cb0e229d-de6d-40cb-b407-d6028114625f │ ➖     │ default │ default        │ default      ┃
┠────────┼────────────┼──────────────────────────────────────┼────────┼─────────┼────────────────┼──────────────┨
┃        │ stack_0    │ cf02d1af-0943-4727-98fd-fb2b06defc4d │ ➖     │ default │ default        │ default      ┃
┠────────┼────────────┼──────────────────────────────────────┼────────┼─────────┼────────────────┼──────────────┨
┃        │ stack_1    │ 27c0f403-5bff-49a6-97da-9eb5c46f7958 │ ➖     │ default │ default        │ default      ┃
...

┠────────┼────────────┼──────────────────────────────────────┼────────┼─────────┼────────────────┼──────────────┨
┃        │ stack_49   │ 35abdd36-710f-4414-9c4b-a33fa9496c47 │ ➖     │ default │ default        │ default      ┃
┗━━━━━━━━┷━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━┛
```

An important thing to note, this PR only affects the CLI utility functions and **does not affect** how the pagination works.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by fa9r — APPROVED** [review]
SGFMA

**Review by AlexejPenner — APPROVED** [review]
:seal:

**Comment by bcdurak** [comment]
@stefannica I have adjusted the code based on our discussions. Now, the active model will only be put on top of the list **if and only if** there is no filtering, sorting, or pagination happening. (Used the click context to figure out if the default values were used or not)

**Review by stefannica — APPROVED** [review]
LGTM

**Pull request merged**
