### PR TITLE
Seldon Core V2 

### PR DESCRIPTION
**Pull request by safoinme**
## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
What a machine, over the weekend implementation!!! <3 

Amazing! I have not seen the code yet but i see two things id like to give quick feedback on:

1. Tests and docs are missing but i assume youd take that into the sprint
2. Maybe we should let @edshee take a look already for early feedback. For that, a nice example might be nice

**Comment by edshee** [comment]
Awesome work @safoinme . If you create some basic docs for it I'm happy to build an end-to-end example based on the previous one (for core v1).

**Comment by safoinme** [comment]
Thank you so much for the feedback @edshee, That would be awesome! right now, this branch has basically the same functionalities supported in V1. However, we are exploring the possibility of supporting more than just the `model` deployment but maybe also `Pipelines` and `Experiments`.

**Comment by edshee** [comment]
If you're able to add support for pipelines that'd be absolutely awesome. Seems like there would be an ideal 1:1 mapping between steps:models and pipelines:pipelines.

**Comment by Johnyz21** [comment]
Heya 😊
Really love the work that's done here! Is there a timeline for getting this change merged in as we're very eager to test out Seldon Core V2 with ZenML

**Pull request closed without merging**
