### PR TITLE
Fix/set env variables before installing packages

### PR DESCRIPTION
**Pull request by lopezco**
## Describe changes
While building a Docker file, I  need to set the environment variables before installing the packages as some of the ENV vars change the way the packages are installed.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- {x] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

### CODE REVIEW

**Review by schustmi — CHANGES_REQUESTED** [review]
Changes look good to me, you'd just need to rebase on develop and adjust the target branch of this PR so we can merge it!

**Comment by lopezco** [comment]
@schustmi It is ok now?

**Review by schustmi — CHANGES_REQUESTED** [review]
Yes looks good now. I thought of one more change that we could make to this:
I would suggest to keep the following lines
```python
if download_files:
  lines.append(f"ENV {ENV_ZENML_REQUIRES_CODE_DOWNLOAD}=True")
```
below the apt/pip installs. The reason for this (and also why we set the environment variables as late as possible in the first place) is to improve the Docker caching for repeated builds.

**Comment by lopezco** [comment]
@schustmi that is true, I just pushed the changes to leave only user-set environment variables before apt/pip installs

**Review by schustmi — APPROVED** [review]
Perfect, thanks!

**Review by fa9r — APPROVED** [review]

**Pull request merged**
