### PR TITLE
Fix local airflow example

### PR DESCRIPTION
**Pull request by schustmi**
## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
- Fix airflow orchestrator and local airflow example

### CODE REVIEW

**Review by AlexejPenner — APPROVED** [review]
Let the air flow again!

**Review by AlexejPenner — COMMENTED** [review]
Running it locally it did not work - lets investigate before we merge

**Review by alex-zenml — APPROVED** [review]
Looks like it's working now, given a fresh environment.

**Comment by htahir1** [comment]
I also checked on WSL (Linux on Windows) and it works like a charm

**Review by AlexejPenner — APPROVED** [review]
Created a new venv -> poetry installed you branch -> followed README instructions of the example -> runs with no issues :smile: -> lgtd :wink:

**Pull request merged**
