### PR TITLE
Bugfix for the count queries after the sqlmodel upgrade

### PR DESCRIPTION
**Pull request by bcdurak**
## Describe changes
- Fixed the `count` query in the SQL ZenStore
- Pinned the starlette version for the airflow integration as it would create a version mismatch.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [X] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by safoinme — APPROVED** [review]
LGTM :shipit:

**Comment by safoinme** [comment]
@bcdurak some conflict in dependencies

**Comment by strickvl** [comment]
@bcdurak should / can this be closed, or will it migrate over to the pydantic branch?

**Comment by bcdurak** [comment]
@strickvl closing the issue now, transferring the changes to the pydantic mega branch.

**Pull request closed without merging**
