### PR TITLE
Fix Pandas Materializer Index

### PR DESCRIPTION
**Pull request by safoinme**
## Describe changes
Fix pandas materializer indexing by forcing the save of the index as an extra column and loading it back when reading CSV.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
Is it possible to write some tests for this please with various dataframes and cases?

**Review by htahir1 — CHANGES_REQUESTED** [review]
Great that looks good now. I just have one wish to test this with a datetime index just to check it out!

**Review by htahir1 — COMMENTED** [review]
Ok and now last question: What happens to users who have materialized the dataframes with older versions of ZenML? :D

**Comment by safoinme** [comment]
@htahir1 it depends on what the older version means if it's pre-0.30 which was done only using pyarrow it will raise an import error telling them to `pip install pyarrow` if it's post-0.30 I think nothing huge changes on the `CSV` save to cause errors! the save with pyarrow is still the best way as it is more efficient and save the whole state of the frame so they still get a warning that they must install it to get the best way

**Review by htahir1 — APPROVED** [review]
As long as it works on all versions then im happy to go!

**Review by schustmi — APPROVED** [review]

**Pull request merged**
