### PR TITLE
Fixing the error messages when fetching entities

### PR DESCRIPTION
**Pull request by bcdurak**
## Describe changes
I have improved the error messages when `get`ting entities by name, ID, or prefix.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — CHANGES_REQUESTED** [review]
The changes so far are looking good, though to bring it in line with other parts of the CLI could you make sure that the raised errors are handled in the CLI? I.e. like what happens with `zenml stack delete ...` for a non-existent stack. Specifically, I don't believe the user should be exposed to a full stacktrace when updating a non-existent component.

Also, could you add a test for this scenario in `test_client.py` (it is covered already in the corresponding CLI test). We don't have a test for it yet.

**Comment by bcdurak** [comment]
You are absolutely right. The only reason why we have not invested more time into the tests is the upcoming `list, prefix matching, and pagination` branch. With those changes, these two functions will completely change. Until then I would propose keeping it as it is in terms of tests.

As for the stack trace, I think I have a solution. But, it is a generalized solution. It would help us remove all the 
```
try:
    something()
except ThisError as e:
    cli_utils.error(str(e))
except ThatError as e:
    ... 
    cli_utils.error(e)
```
blocks and clean up the CLI code. However, it might make sense then to do it in a separate PR as it would be significantly larger in size.

**Comment by strickvl** [comment]
I leave it to your better judgement about the tests, but for now I'd just make the non-generic fix for the CLI probably. I did like the sample / suggestion you sent to me over discord, but I would not invest all the effort to create the generic fix that's applicable everywhere, since that seems like it'd take a bit of time / effort to implement..

**Comment by bcdurak** [comment]
@strickvl I tried to fix as many occurrences as I can find.

**Review by strickvl — APPROVED** [review]
Thanks. Looks good to go now!

**Review by AlexejPenner — APPROVED** [review]
:seal:

**Pull request merged**
