### PR TITLE
Update kubeflow.md

### PR DESCRIPTION
**Pull request by abohmeed**
Fixes a typo

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — APPROVED** [review]
Thank you for catching this!

**Review by schustmi — APPROVED** [review]

**Comment by strickvl** [comment]
This change will have to be merged into `develop` and not `main`. Could you make that change, @abohmeed ?

**Comment by abohmeed** [comment]
@strickvl done

**Comment by schustmi** [comment]
@abohmeed This PR now contains some files that are probably due to the fact that you branched off of our main branch, could you please also rebase to develop to we're only merging the typo fix. Thanks!

**Comment by abohmeed** [comment]
> @abohmeed This PR now contains some files that are probably due to the fact that you branched off of our main branch, could you please also rebase to develop to we're only merging the typo fix. Thanks!

I updated the branch, is that what you mean?

**Comment by schustmi** [comment]
Something still seems off, as your PR changes two files instead of the one that fixes the typo.

**Comment by htahir1** [comment]
I think its fine - ill merge this now and fix the develop branch!

**Pull request merged**
